### ISSUE TITLE
jitsi-meet server with selfsigned certificate

### ISSUE THREAD

**Issue by manang** [fpw23/telimed#2]
Hi,
I've installed jitsi meet using this guide:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
I'm using a self signed certificate and I'm trying to use your project with my own jitsi-meet server.

I tried to use my url
<my_ip>8443 instead of beta.meet.jit.si and I obtain the following error:
`WebSocket connection to 'wss://<my-ip>/xmpp-websocket?room=workshop014' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
2020-10-28T09:58:50.873Z [modules/xmpp/strophe.util.js] <Object.r.Strophe.log>: Strophe: Websocket error [object Event]`

Can you tell me where is the error?
thanks

Angelo

**Comment by fpw23** [comment]
I have moved off this project so I don't have anything setup locally to test out your issue but it looks like there is a problem with websockets.  If I remember correctly Jiti uses a ws server for the chat features that are baked into the core api.  My guess is on your docker container you have to map some more ports.  Here is a something from the jitsi community forum about it:

https://community.jitsi.org/t/ports-5222-5269-5280-5347/36862/3

To be sure I would look at the dev tools and see the network tab, it should show all traffic the page attempts to load and if there are any errors.

**Comment by manang** [comment]
which port do I have to open?
thanks

**Comment by manang** [comment]
I changed the port from 8443 to 443 in docker jitsi meet.
I'm using a self signed certificate.
now the error is the following:

`WebSocket connection to 'wss://<my-ip>/xmpp-websocket?room=workshop014' failed: Error in connection establishment: net::ERR_CERT_INVALID`

can you tell me how I can disable the cert verification?
Thank you very much

Angelo

**Comment by manang** [comment]
Is the websocket mandatory?
thanks

**Comment by manang** [comment]
they have just updated the docker-compose, so you can use the websocket.
If I use this approach I obtain an err_cert_invalid.
I hope you can help me.
Thank

**Comment by fpw23** [comment]
The version of jitsi I used when I made this demo required the websockets, it needs them to do the chat feature using XMPP.  I don't know much about it, I just focused on the audio/video part of jitsi.  Did you try opening the ports on the docker container from that link above?

![image](https://user-images.githubusercontent.com/6162217/97569315-38580680-19b5-11eb-87c3-ef058112713c.png)

If you use the dev tools on your browser and look at the network tab you should see more details on the failure.

![image](https://user-images.githubusercontent.com/6162217/97570724-984ead00-19b5-11eb-8814-a6aff4b66602.png)

You can set the filter for WS (WebSockets) and see the exact port it is trying to reach and details on the failure

**Comment by manang** [comment]
I think that my problem is more about the selfisgned certificate.
I opened the ports of WS, if you tell me how I can use your application with selfsigned certs I can solve the issue.
Thank you very much
Angelo

**Comment by fpw23** [comment]
well, self signed is hard because the browser is going to reject it usually, the only thing I can think of trying it making sure everything is bound to localhost.  Chrome has a security feature where if the address is localhost instead of an ip it will allow you to do insecure things like use the camera without ssl.  Maybe where you set the [server url](https://github.com/fpw23/telimed/blob/master/src/App.js#L180) make sure it says localhost and not an ip address.  You would also have to make sure the docker jitsi is bound to the internal 127.0.0.1 (localhost) side as well.

I did not run into these issues because I only used the beta jitsi address for my tests.  In prod my network guy setup the jitsi server with a non self signed cert so everything just worked.

**Comment by manang** [comment]
Hi, I don't undestand why jitsi-meet repo can connect to the videobridge server with self signed certificates and this application no.
thanks for your help

**Comment by fpw23** [comment]
If you use this app and point it to the [public jitsi server](https://github.com/fpw23/telimed/blob/master/src/App.js#L14) does it work for you?

**Comment by manang** [comment]
Hi, with the public jitsi server yes, it works,
I'm noticing this:
https://github.com/jitsi/jitsi-meet/blob/9fbb35b6e18536a85fc608b0685c71744880a651/webpack.config.js#L36

This is my first time with webpack, I'm noticing that jitsi-meet define a proxy that permits to avoid the cert error.
I don't know if we can do the same with your project.

thank you very much

**Comment by fpw23** [comment]
For this project I just used [create-react-app](https://reactjs.org/docs/create-a-new-react-app.html) which hides the complexity of webpack.  If you want to change webpack settings you will have to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) or use a [tool to change the config](https://github.com/gsoft-inc/craco).  Both will take some doing and outside my bandwidth for this project.  Sorry.

**Comment by manang** [comment]
Hi,
this is an update of you can use this app with jitsi in docker (https://github.com/jitsi/docker-jitsi-meet).
In order, you need:
trusted certified (let's encrypt is available in the docker-jitsi-meet installation, or you have to create self signed certificates + CA authority)
you have to use a configuration file like this https://meet.jit.si/config.js.
In my example I'm not using the websocket, but the rest APIs.
I will push a simple modification next week, maybe it can help other people.

Thanks a lot for your help

**Comment by fpw23** [comment]
Sweet!   Thanks for sharing, look forward to seeing your changes!
